# Changes here will be overwritten by Copier
_commit: v0.2.5
_src_path: gh:ninanor/template-python
author_name: ninanor
debug: false
default_branch_name: main
docker: false
email: ninanor@nina.no
notebook: false
project_name: radar-migration
project_slug: radar-migration
repo_name: radar-migration
repo_org: ninanor
template_type: python
type_annotations: false
