db:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: postgres
  schema: public

bucket:
  name:
  endpoint:
  secret_key:
  access_key:
  url_style:

deployment_id: 

schemas:
